#!/bin/bash -
#===============================================================================
#
#          FILE: callnt.sh
#
#         USAGE: ./callnt.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Rayiik (), dsimon_aas@hotmail.com
#  ORGANIZATION:
#       CREATED: 08/17/2020 01:48:05 AM
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

callnt () {
  cat "$("$HOME"/project/namet)" \
    | colorize
  }

callnt
