#!/bin/bash -
#===============================================================================
#
#          FILE: fzrm.sh
#
#         USAGE: ./fzrm.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Rayiik (), dsimon_aas@hotmail.com
#  ORGANIZATION:
#       CREATED: 09/03/2020 12:42:42 AM
#      REVISION:  ---
#===============================================================================
set -e
#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

color1="$(tput bold ; tput setaf 1)"
color9="$(tput bold ; tput setaf 7)"
#nc="$(tput sgr0)"
_origloc="$PWD"

 echo "$color9 $(fd -uu -t f . -d3)"  | \
  fzf --bind='f9:execute:rm {+} -R' \
  --bind='f8:execute:mv {) ~/tmp/' \
  --bind="f7:reload:echo $color9 $(fd -uu -t f -d3 .)" \
  --bind="f6:reload:echo $color1 $(fd -uu -t d -d3 .)"  \
  --bind="ctrl-v:execute:$EDITOR {}" \
  --bind="f11:reload: {  \
    (test -d {}; cd {}) || (echo $color1 $(fd -uu -t d -d3 .); cd {})
  }" \
    --bind="f12:reload:cd / || exit; echo $color1 $(fd -uu -t d -d3 .)" \
    --bind="ctrl-alt-u:reload:cd ..; $color1 $(fd -uu -t d -d3 .)"  \
  --header="for help menu use ctrl-alt-o \n
    $(fline)" \
  --bind="ctrl-alt-o:preview:${_preview:-"{
echo  ACTIONS
echo \"$(fline)\"
echo f6:dir search
echo f7:file search
echo f8:mv to tmp
echo f9: rm  selected
echo f11:change to target dir
echo f12: return to orignonal directory
echo ctrl-alt-u: change up 1 directory
echo ctrl-alt-d: change to target dircetory
echo ctrl-v: open in editor
echo ctrl-h: open selection in manpage
echo alt-a: select all
echo ctrl-alt-h: open keybindings in preview
echo \"$(fline)\"
echo MOVEMENT
echo \"$(fline)\"
echo ctrl-u:half page up
echo alt-u: page up
echo ctrl-d: half page down
echo alt-d: page down
echo ctrl-s: preview page down
echo ctrl-a: preview page up
echo ctrl-p: toggle preview
echo alt-h: shift cursor left in query
echo alt-l: shift cursor right in query
echo ctrl-j: down in selection
echo ctrl-k: up in selection
}"}" \
  --bind="ctrl-alt-d:reload:cd $_origloc; echo $color1 $(fd -uu -t d -d3 .)" \
  --preview="{
  echo {}; fline
for _file in *{}*; do
  [[ test -d $_file && fd -uu -t d -d 1 . $(pwd)/$_file) ]] || \
  [[ test -f $_file && nvimpater $file) ]] || \
  [[ test -n $(rg -tpicture . "$(pwd)/$file") && fbv $_file ]] || \
    $(jp2a /home/rayiik/fzfscripts/MTTW-1.jpg)
}"

#fd -uu -t f | \
#  fzf --bind='f9:execute:unco record -- rm {+} -R' \
#  --bind='f8:execute:mv {) ~/tmp/' \
#  --bind='f7:reload:fd -uu -t f' \
#  --bind='f6:reload:fd -uu -t d' \
#  --preview='{
# (test -d {} && ls -R {}) || (test -f && nvimpager {})
#}'
