#!/bin/bash -
#===============================================================================
#
#          FILE: uzd.sh
#
#         USAGE: ./uzd.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Rayiik (), dsimon_aas@hotmail.com
#  ORGANIZATION:
#       CREATED: 12/12/2020 07:46:35 AM
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error


for file in ./*;
do
    unzip "$file"
done

