#!/bin/bash !
fzfcmp () {
    local term
    local FZF_DEFAULT_COMMAND
    FZF_DEFAULT_COMMAND="infocmp $TERM -1"
    term="$(
    infocmp "$TERM" -1 | tr '=' '\n' | \
       tr '\t' '' | \
      sed 's/,$//' | fzf \
      --preview='man terminfo | rg -C10 -e {q}' \
        --preview-window='right:80:wrap' --phony \
        --bind="f9:replace-query+preview:man terminfo | rg -C1 -e {q}" \
            )"

READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT} $(awk -F= '{print $1}' <<<"${term:-''}" \
    | sed 's/,$//') ${READLINE_LINE:$READLINE_POINT}"

    if test -n "$(rg -e 'echo' <<<"$READLINE_LINE")"; then
        READLINE_LINE=$READLINE_LINE; else
READLINE_LINE="echo -e \"$READLINE_LINE\""
    fi

  READLINE_POINT=$(( READLINE_POINT + ${#term} ))
unset term
}
bind -x '"\et": fzfcmp'
