#!/usr/bin/env bash
#alias

alias pacup="sudo pacman -Syyu --needed --noconfirm | tee -a /home/rayiik/tmp/pacup.tmp | \
  colorize || exit 2 "
  alias fdm="findmnt"
alias python='python3'
alias mkpkg='makepkg -si | tee >./pkglog | colorize'
alias rm="rm -I"
alias mv='mv -I'
alias ffox='firefox && disown -a &'
alias tbird='thunderbird && disown -a &'

gimp () {
    gimp "$1" && disown -a &
}
echo 'this is bash aliases'
alias findmnt='findmnt | colorize'
alias cp='cp -i'
alias fd='fd --color=always'

pacfunc () {

  IFS=$'\n'
  for line in $(makepkg -si | tee -a &>./pkglog 2>/dev/null 1>/dev/stdout); do
   for word in $line; do
     if [[ "$word" == 'error' ]]; then
       printf '%s' "${word//$red $word $nc/} 2>&1 "; elif
       [[ "$word" == 'warning' ]]; then
    printf '%s' "${word//$magenta $word $nc/} 2>&1 "; elif
        [[ "$word" == 'no' ]]; then
    "${word//$blue $word $nc/}"; else
    printf '%s' "$word"
     fi
   done
 done
}
alias pip='pip3'
alias mycs='mycroft-start'
alias mpkg='makepkg -si | colorize | tee -a ./pkglog'
alias info='info --vi-keys'

alias cdm='cd /home/rayiik/project/Man-fzf-scripts'
alias nvp='nvimpager'
alias wcl='wl-clip'
alias wcp='wl-copy'
alias wpst='wl-paste'
alias ap3m='ap3m.sh'
alias ip='ip --color=always'
alias acr='arch-chroot'
alias diff='diff --color=always'
alias cdf='zd -f'
alias cda='_fda'
alias nvi='nvim'
alias nvmi='nvim'
alias nivm='nvim'
alias cdp='cd /home/rayiik/project/Man-fzf-scripts'
alias pwd='$PWD '
alias sudo='sudo '
alias mt='mount'
alias ..='zd ..'
alias ct='cat -s'
alias dir='dir --color=auto'
alias curl='curl --user-agent "noleak" '
alias vi='vim'
alias shred='shred -zf'
alias lsd='lsd -a'
alias vm='nvim'
alias l='lsd -aF --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias cds='cd /home/rayiik/fzfscripts'
alias cdbf='cd /home/rayiik/coms/scripts/'
alias pacman-rem='sudo pacman -R --unneeded --recursive --nosave --color=always'
alias pacman-find='sudo pacman -Qiqe >> packages'
alias ls='ls -A -F --color=always --group-directories-first'
alias lla='exa -A -F'
alias reflector='sudo reflector --sort rate --latest 20  --save /etc/pacman.d/mirrorlist'
alias ps1='ps -e | fzf | rg '
alias vdir='vdir --color=auto'
alias ppng='prettyping'
alias container='docker\ container'
alias nv='nvim'
alias rs='rsfetch '
alias mkdir='uu-mkdir '
alias mkfifo='uu-mkfifo '
alias mknod='uu-mknod '
alias mv='uu-mv '
alias nice='uu-nice '
alias nl='uu-nl '
alias nproc='uu-nproc '
alias nohup='uu-nohup '
alias paste='uu-paste '
alias pathchk='uu-pathchk '
alias printenv='uu-printenv '
alias pinky='uu-pinky '
alias ptx='uu-ptx '
alias printenv='uu-printenv '
alias readlink='uu-readlink '
alias realpath='realpath '
alias relpath='relpath '
alias rm='uu-rm -I'
alias rmdir='uu-rm -I '
alias seq='uu-seq '
alias shred='uu-shred '
alias shuf='uu-shuf '
alias rsc='rustscan -b 8092'
alias sleep='uu-sleep '
alias stat='uu-stat '
alias stdbuf='uu-stdbuf '
alias sum='uu-sum '
alias sync='uu-sync '
alias tac='uu-tac '
alias tee='uu-tee '
alias timeout='uu-timeout '
alias touch='uu-touch '
alias tr='uu-tr '
alias truncate='uu-truncate '
alias tsort='uu-tsort '
alias tty='uu-tty'
alias uname='uu-uname '
alias unexpand='uu-unexpand'
alias uni='uu-unique '
alias unlink='uu-unlink '
alias stx='unset DISPLAY; startxfce4'
alias users='uu-users'
alias comc='compgen -c'
alias cl='cdls'
alias wc='uu-wc'
alias who="uu-who"
alias whoami='uu-whoami | colorize'
alias cargo='cargo --color=always'
alias yes='uu-yes'
alias ll='lsd -laF --color=auto'
alias di='pyls'
alias bat1='bat --color=always --theme=solarized-light'
alias pacsc='sudo pacman -Slq | fzf -m --preview pacman -Si {1} | xargs -ro sudo pacman -S'
# alias coms='sh ~/.scripts/func/fini/coms.sh'
alias comc='compgen -c'
# alias awk2="awk 'seen [$0]++'"
alias ...='zd ..'
alias cd1='cd /home/rayiik/coms/scripts/; ls -a'
alias cd2='cd /home/rayiik/fzfscripts; ls -a'
alias fdl='fdisk -l | colorize'

# alias coms='sh ~/.scripts/func/fini/coms.sh'
alias sssid='sudo iw dev wlo1 scan | rg -C0 --no-filename SSID: | sort -u'
alias shf='ssh rayiik@192.168.1.225'
