#!/bin/bash
zombilist=( "$(while read line;
do
if [[ -n "$(grep -i z <<<"$line")" ]]; then echo "$line" | awk '{print $2}'
    fi; done <<<"$(ps aux)")" )
echo "${zombilist[*]##PID}" | tr '\n' ' ' | xargs -r sudo kill -s SIGKILL
unset zombilist
