#!/bin/bash -
#===============================================================================
#
#          FILE: bootmods.sh
#
#         USAGE: ./bootmods.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Rayiik (), dsimon_aas@hotmail.com
#  ORGANIZATION:
#       CREATED: 08/07/2020 01:08:10 AM
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error
_rgcolor="rg --no-filename --passthru"
lsmod | \
  awk 'NF==3{print $1}' | \
  fzf --preview="modinfo {} | \
   $_rgcolor  -e '^[a-z A-Z].*:\s' -e '^sig_key:\s' \
   -e '^sig_hashalgo:\s' \
   -e '^sig_id:\s' " | \
  sed 's/\n/\nMODULES=(/' | cat

